FROM clamav/clamav:1.4.3@sha256:75fb5fd95fcbe1d7e6d240c369c1572b686ee2c95949d1042b5148de8eddebb4
RUN sed -i '/^StreamMaxLength /d; /^MaxFileSize /d; /^MaxScanSize /d' /etc/clamav/clamd.conf && \
    printf '\nStreamMaxLength 100000000\nMaxFileSize 100000000\nMaxScanSize 200000000\n' >> /etc/clamav/clamd.conf
